## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVIDER-INFRA-SETUP
    - DIRECTOR-HEALTH-CHECK
    - USER-CLUSTER-SETUP
    - USER-CLUSTER-CONNECT
    - CLUSTER-CLEANUP
  
## Setup the kubernetes cluster
cluster-create:
  image: harshshekhar15/gitlab-job:v5
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/1-cluster-setup/aws-eks
    - ./stages/1-cluster-setup/aws-eks
  artifacts:
    when: always
    paths:
      - .kube/

## Deploy director-onprem
director-deploy:
  image: harshshekhar15/gitlab-job:v5
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/2-provider-infra-setup/dop-deploy
    - ./stages/2-provider-infra-setup/dop-deploy
  artifacts:
    paths:
      - .kube/

# director health check jobs
maya-io-server-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/maya-io-server-check
    - ./stages/3-director-sanity-check/maya-io-server-check
  artifacts:
    paths:
      - .kube/

maya-ui-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/maya-ui-check
    - ./stages/3-director-sanity-check/maya-ui-check
  artifacts:
    paths:
      - .kube/

od-elasticsearch-logging-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/od-elasticsearch-logging-check
    - ./stages/3-director-sanity-check/od-elasticsearch-logging-check
  artifacts:
    paths:
      - .kube/

od-kibana-logging-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/od-kibana-logging-check
    - ./stages/3-director-sanity-check/od-kibana-logging-check
  artifacts:
    paths:
      - .kube/

table-manager-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/table-manager-check
    - ./stages/3-director-sanity-check/table-manager-check
  artifacts:
    paths:
      - .kube/

chat-server-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/chat-server-check
    - ./stages/3-director-sanity-check/chat-server-check
  artifacts:
    paths:
      - .kube/

cloud-agent-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/cloud-agent-check
    - ./stages/3-director-sanity-check/cloud-agent-check
  artifacts:
    paths:
      - .kube/

mysql-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/mysql-check
    - ./stages/3-director-sanity-check/mysql-check
  artifacts:
    paths:
      - .kube/

maya-grafana-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/maya-grafana-check
    - ./stages/3-director-sanity-check/maya-grafana-check
  artifacts:
    paths:
      - .kube/

memcached-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/memcached-check
    - ./stages/3-director-sanity-check/memcached-check
  artifacts:
    paths:
      - .kube/

## cortex infrastructure components jobs
alertstore-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/alertstore-check
    - ./stages/3-director-sanity-check/alertstore-check
  artifacts:
    paths:
      - .kube/

alertstore-tablemanager-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/alertstore-tablemanager-check
    - ./stages/3-director-sanity-check/alertstore-tablemanager-check
  artifacts:
    paths:
      - .kube/

alertmanager-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/alertmanager-check
    - ./stages/3-director-sanity-check/alertmanager-check
  artifacts:
    paths:
      - .kube/

cassandra-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/cassandra-check
    - ./stages/3-director-sanity-check/cassandra-check
  artifacts:
    paths:
      - .kube/

distributor-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/distributor-check
    - ./stages/3-director-sanity-check/distributor-check
  artifacts:
    paths:
      - .kube/

ingestor-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/ingestor-check
    - ./stages/3-director-sanity-check/ingestor-check
  artifacts:
    paths:
      - .kube/

querier-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/querier-check
    - ./stages/3-director-sanity-check/querier-check
  artifacts:
    paths:
      - .kube/

ruler-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/ruler-check
    - ./stages/3-director-sanity-check/ruler-check
  artifacts:
    paths:
      - .kube/

configs-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/configs-check
    - ./stages/3-director-sanity-check/configs-check
  artifacts:
    paths:
      - .kube/

configs-db-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/configs-db-check
    - ./stages/3-director-sanity-check/configs-db-check
  artifacts:
    paths:
      - .kube/

ingress-nginx-check:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-HEALTH-CHECK
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/3-director-sanity-check/ingress-nginx-check
    - ./stages/3-director-sanity-check/ingress-nginx-check
  artifacts:
    paths:
      - .kube/

cluster-setup-check:
  image: harshshekhar15/gitlab-job:v5
  stage: USER-CLUSTER-SETUP
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/4-user-cluster-setup/cluster-create-check
    - ./stages/4-user-cluster-setup/cluster-create-check
  artifacts:
    when: always
    paths:
      - .kube/

create-apikey-check:
  image: harshshekhar15/gitlab-job:v3
  stage: USER-CLUSTER-CONNECT
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/5-cluster-connect-check/create-apikey-check
    - ./stages/5-cluster-connect-check/create-apikey-check

trrc01-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: USER-CLUSTER-CONNECT
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/5-cluster-connect-check/cluster-connect-check
    - ./stages/5-cluster-connect-check/cluster-connect-check
  artifacts:
    when: always
    paths:
      - .kube/
      - .gcp/

client-components-check:
  image: harshshekhar15/gitlab-job:v3
  stage: USER-CLUSTER-CONNECT
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/5-cluster-connect-check/client-components-check
    - ./stages/5-cluster-connect-check/client-components-check

director-self-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: SELF-CLUSTER-CONNECT
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/6-self-cluster-connect/self-connect-cluster-check
    - ./stages/6-self-cluster-connect/self-connect-cluster-check

# Kubernetes cluster cleanup
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v5
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/13-cluster-setup/delete-cluster
    - ./stages/13-cluster-setup/delete-cluster
  artifacts:
    when: always
    paths:
      - .kube/

prerequisites-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v5
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/13-cluster-setup/delete-pre-requisite
    - ./stages/13-cluster-setup/delete-pre-requisite
  artifacts:
    when: always
    paths:
      - .kube/