## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVIDER-INFRA-SETUP
    - CLUSTER-CLEANUP
  
## Setup the kubernetes cluster
cluster-create:
  image: harshshekhar15/gitlab-job:v4
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/1-cluster-setup/aws-eks
    - ./stages/1-cluster-setup/aws-eks
  artifacts:
    when: always
    paths:
      - .kube/

## Deploy director-onprem
director-deploy:
  image: harshshekhar15/gitlab-job:v4
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/2-provider-infra-setup/dop-deploy
    - ./stages/2-provider-infra-setup/dop-deploy
  artifacts:
    paths:
      - .kube/

## Kubernetes cluster cleanup
# cluster-create:
#   image: harshshekhar15/gitlab-job:v4
#   stage: CLUSTER-SETUP
#   script:
#     - chmod 755 ./stages/13-cluster-setup/aws-eks
#     - ./stages/13-cluster-setup/aws-eks
#   artifacts:
#     when: always
#     paths:
#       - .kube/