apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: mysql-dmaas-jiva
  labels:
    app: wordpress
spec:
  storageClassName: openebs-jiva-default-rep-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15G
